aaa
troyfrc3952/Basic-Robot-Code pull request #1
Opened 2022-10-04 20:18 UTC by LFC6times

Comment here

2022-10-04 20:18 UTC, ChosenAN commented
omg ur so funny and quirky and awesome and cool

2022-10-04 20:18 UTC, baconman125 commented
lol

2022-10-04 20:20 UTC, crescendont commented
hi

2022-10-04 20:21 UTC, Meis2gucci commented
puru jain>>>

2022-10-04 20:21 UTC, siIverfish commented
hi

2022-10-04 20:22 UTC, mousrt commented
g

2022-10-04 20:22 UTC, codestdoufu commented
hola guys im trolling

2022-10-04 20:23 UTC, siIverfish commented
wow

2022-10-04 20:24 UTC, DJamesRoboticsGitHub commented
How much wood would a woodchuck chuck if a wood chuck could chuck wood?

2022-10-04 20:24 UTC, Rohan-KK commented
a lot of wood

2022-10-04 20:24 UTC, codestdoufu commented
comment for free robux

2022-10-04 20:25 UTC, DJamesRoboticsGitHub commented
no its minecoins or bust

2022-10-04 20:25 UTC, Zqzheng22 commented
:D

2022-10-04 20:25 UTC, t08tina commented
comment :)

2022-10-04 20:40 UTC, yavko commented
Deez

2022-10-04 20:41 UTC, yavko requested changes
Its not sus enough

2022-10-05 03:53 UTC, soh3e commented
swaggin

2022-10-05 04:12 UTC, yavko requested changes

2022-10-05 04:12 UTC, yavko commented on h/amongus.txt
> +bruh git
Needs more sussyness

2022-10-05 04:13 UTC, yavko commented
> swaggin

I disagree, you are contributing 😎

2022-10-06 03:58 UTC, astrolight7 commented
hello

2022-10-06 04:53 UTC, Tankmaster48 commented
leave a comment

2022-10-06 04:58 UTC, yavko commented
amogus

2022-10-06 20:04 UTC, lukeprakarsa commented
hi :D

2022-10-06 20:16 UTC, lickriu commented
sup foo

2022-10-06 20:19 UTC, justkevin commented
hi

2022-10-06 20:22 UTC, NotCraigGu commented
hi

2022-10-07 05:13 UTC, Seyed-Madaen commented
hee hee

2022-10-07 05:17 UTC, yavko commented
> hee hee

sus

2023-10-17 20:04 UTC, closed without merging